### ISSUE TITLE
Does this plugin sync new library items or only watch states?

### ISSUE THREAD

**Issue by rastarr** [jellyfin/jellyfin-plugin-trakt#161]
I had Trakt plugin installed on my Kodi and also within Jellyfin
When disabling the Kodi instance, I was hoping the Jellyfin plugin would then take care of everything including adding new library items.
It seems that is not the case - or I have an issue

Can someone please advise so I am clear?

**Comment by Shadowghost** [comment]
The plugin adds items to your collection if you enable it for your user (this happens when new items are added for the new items and when you running the sync task).
Keep in mind though that this heavily depends on proper TMDB and IMDB tagging of your items (there is a fallback to episode and season number but that's often not reliable if you use another naming scheme).

**Comment by rastarr** [comment]
> The plugin adds items to your collection if you enable it for your user (this happens when new items are added for the new items and when you running the sync task). Keep in mind though that this heavily depends on proper TMDB and IMDB tagging of your items (there is a fallback to episode and season number but that's often not reliable if you use another naming scheme).

Ahh ok, there was no scheduled task which looks like the issue for me. thanks so much for the reply/answer
