### ISSUE TITLE
[Plugin Disabled] Issue with spamming Trakt API

### ISSUE THREAD

**Issue by rudf0rd** [jellyfin/jellyfin-plugin-trakt#174]
Hey we've been tracking an issue on our API that an app is hammering the scrobble/start endpoint and concluded it's the Jellyfin plugin.   We just revoked the Jellyfin API key and everything leveled out on the servers.

Can you guys help explain what's going on with the high frequency of scrobble/start calls?  Please let us know how we can help get your plugin back online.

**Comment by rudf0rd** [comment]
It's somewhere in the vicinity of the end of August.  It starts ramping up around 8/20.  I am basing this guess on overall hits on the api endpoint and not specific to the Jellyfin api key, unfortunately.

Can you give me a basic scrobble flow for the plugin?  As we dig in, we're noticing more than just the Jellyfin plugin are hitting the scrobble/start endpoint more than once during a play.

**Comment by anthonylavado** [comment]
@rudf0rd While SenorSmartyPants has contributed to this repo, they're not on the team proper. I believe our server and plugin folks are aware of this issue atm, I'm not sure when they'll have a moment to comment on the flow.

It's interesting to note if traffic ramps up as of Aug 20th. The last two releases of the plugin would have been Sep 2nd (version 20), and before that was May 28th (version 19). So nothing that _directly_ lines up.

**Comment by SenorSmartyPants** [comment]
That's true I'm not on the team proper, but I thought it was a good question to ask. And I was curious to see if the time lined up with any changes I might have contributed so I could help fixing them. 

Big Thanks to the JF and Trakt teams!

**Comment by rudf0rd** [comment]
<img width="2042" alt="Screen Shot 2022-10-17 at 12 49 36 PM" src="https://user-images.githubusercontent.com/71062/196269602-993ecbc9-6a86-40a7-bd9d-9f1bd39b00e5.png">

Figured out a better way to see when the ramp occurred.  It definitely started in May.

**Comment by oddstr13** [comment]
Looks like events might be pushed at most every 10s?

https://github.com/jellyfin/jellyfin-plugin-trakt/blob/70a3c3aa4187990ecb2f95667f7b96ae659ce801/Trakt/Helpers/LibraryManagerEventsHelper.cs#L52-L56

But that probably also means it's updating playback position every 10s.
I haven't really dug into this plugin before, so I'm not familiar with how the internals work.

**Comment by Gylesie** [comment]
I am not a Jellyfin team member nor on a trakt plugin team. Just trying to add my 2 cents here to try to help resolve this issue. Here it seems that this plugin is calling /scrobble/start endpoint with a currnet progress % every time the media progresses in playback (in my case every 6 seconds):

https://github.com/jellyfin/jellyfin-plugin-trakt/blob/70a3c3aa4187990ecb2f95667f7b96ae659ce801/Trakt/ServerMediator.cs#L363-L368

After reviewing my old logs I can see all the requests and the log messages.

**Comment by foux** [comment]
So just to be sure I understand, we won’t have Trakt on Jellyfin until this issue is resolved?

**Comment by oddstr13** [comment]
This looks like an interesting log call to watch for when debugging, along with whatever follows

https://github.com/jellyfin/jellyfin-plugin-trakt/blob/70a3c3aa4187990ecb2f95667f7b96ae659ce801/Trakt/ServerMediator.cs#L317

**Comment by oddstr13** [comment]
My server which is still running Jellyfin **10.7.7** with Trakt plugin **v12** seems to be behaving just fine (which makes sense, as this was released long before the issue started happening)
<details><summary>Log from 10.7.7</summary>

```
[2022-10-15 17:35:16.089 +00:00] [INF] [62] Trakt.ServerMediator: Playback Started
[2022-10-15 17:35:16.089 +00:00] [DBG] [62] Trakt.ServerMediator: deadbeef appears to be monitoring /mnt/Media/Foo S01E03.mkv
[2022-10-15 17:35:16.089 +00:00] [DBG] [62] Trakt.ServerMediator: Send episode status update
[2022-10-15 18:15:46.861 +00:00] [INF] [59] Trakt.ServerMediator: Playback Stopped
[2022-10-15 18:15:46.866 +00:00] [INF] [59] Trakt.ServerMediator: Item is played. Scrobble
[2022-10-15 18:16:10.419 +00:00] [INF] [20] Trakt.ServerMediator: Playback Started
[2022-10-15 18:16:10.419 +00:00] [DBG] [20] Trakt.ServerMediator: deadbeef appears to be monitoring /mnt/Media/Bar S01E03.mkv
[2022-10-15 18:16:10.419 +00:00] [DBG] [20] Trakt.ServerMediator: Send episode status update
[2022-10-15 18:40:28.800 +00:00] [INF] [71] Trakt.ServerMediator: Playback Stopped
[2022-10-15 18:40:28.800 +00:00] [INF] [71] Trakt.ServerMediator: Item is played. Scrobble
[2022-10-15 18:41:15.953 +00:00] [INF] [51] Trakt.ServerMediator: Playback Started
[2022-10-15 18:41:15.954 +00:00] [DBG] [51] Trakt.ServerMediator: deadbeef appears to be monitoring /mnt/Media/S03E02.mkv
[2022-10-15 18:41:15.954 +00:00] [DBG] [51] Trakt.ServerMediator: Send episode status update
[2022-10-15 19:04:59.201 +00:00] [INF] [59] Trakt.ServerMediator: Playback Stopped
[2022-10-15 19:04:59.206 +00:00] [INF] [59] Trakt.ServerMediator: Item is played. Scrobble
[2022-10-15 19:05:18.657 +00:00] [INF] [29] Trakt.ServerMediator: Playback Started
[2022-10-15 19:05:18.657 +00:00] [DBG] [29] Trakt.ServerMediator: deadbeef appears to be monitoring /mnt/Media/S03E03.mkv
[2022-10-15 19:05:18.657 +00:00] [DBG] [29] Trakt.ServerMediator: Send episode status update
[2022-10-15 19:29:01.260 +00:00] [INF] [34] Trakt.ServerMediator: Playback Stopped
[2022-10-15 19:29:01.260 +00:00] [INF] [34] Trakt.ServerMediator: Item is played. Scrobble
[2022-10-15 19:29:32.636 +00:00] [INF] [6] Trakt.ServerMediator: Playback Started
[2022-10-15 19:29:32.636 +00:00] [DBG] [6] Trakt.ServerMediator: deadbeef appears to be monitoring /mnt/Media/S03E04.mkv
[2022-10-15 19:29:32.636 +00:00] [DBG] [6] Trakt.ServerMediator: Send episode status update
[2022-10-15 19:55:12.112 +00:00] [INF] [87] Trakt.ServerMediator: Playback Stopped
[2022-10-15 19:55:12.113 +00:00] [INF] [87] Trakt.ServerMediator: Item is played. Scrobble
```

</details>

**Comment by Shadowghost** [comment]
Seems like I'm late to the party. I rewrote the syncing to actually do what it was intended to do.
Let me outline what is curtently happening:
* The plugin subscribes to Jellyfin playback events, namely the `PlaybackStart`, `PlaybackProgress` and `PlaybackStopped` events from the SessionManager
* `PlaybackStart` and `PlaybackStop` are quite self explanatory and are only sent once on each event
* Jellyfin continually triggers `PlaybackProgress` events when media is played, sadly this also is the case if the media is paused. So while the player is active and in paused state Jellyfin keeps sending `PlaybackProgress` events

I guess the latter point is where things are going wrong:
* curently we are keeping an internal playback state with the playback position of the last `PlaybackProgress` event to be able to notice pauses, resumes and skips
* Based on the event state we receive from Jellyfin an the state we keep in our local database we only send pause/resume events once:
https://github.com/jellyfin/jellyfin-plugin-trakt/blob/1ed81ff25791c33c33df0649c7c23cf43c6b9ddc/Trakt/ServerMediator.cs#L321
https://github.com/jellyfin/jellyfin-plugin-trakt/blob/1ed81ff25791c33c33df0649c7c23cf43c6b9ddc/Trakt/ServerMediator.cs#L357
* If we are progressing and not paused we compare the runtime ticks of the current state with the one we saved before. If the difference is more than 5 seconds we scrobble to trakt:
https://github.com/jellyfin/jellyfin-plugin-trakt/blob/1ed81ff25791c33c33df0649c7c23cf43c6b9ddc/Trakt/ServerMediator.cs#L383

We are also sending a pause event instead of a stop event if a user interrupts playback before finishing the media:
https://github.com/jellyfin/jellyfin-plugin-trakt/blob/1ed81ff25791c33c33df0649c7c23cf43c6b9ddc/Trakt/ServerMediator.cs#L495

The 10 second timer mentioned earlier is for library events (addition/removal of media) and not for playback tracking.
Library events are also chunked together into batches of 100 items:
https://github.com/jellyfin/jellyfin-plugin-trakt/blob/70a3c3aa4187990ecb2f95667f7b96ae659ce801/Trakt/Api/TraktApi.cs#L292

My guess is that something in the skip calculation (the 5 seconds mentioned earlier) is going wrong but I was quite sure I did test this to not happen - exactly because I didn't want to hammer the API...

I will look into this more over the week but it may take some time.

**Comment by oddstr13** [comment]
@Gylesie are you seeing `Trakt.ServerMediator: Playback skipped` along with the sending movie playback status update message every 6s?

**Comment by rudf0rd** [comment]
@Shadowghost Just to make sure I'm understanding, the scrobble event is intentionally sent every 5s?  If so, that can be removed and this would be fixed I think.  We only require one start event to be sent.

Apologies if I misunderstood!

**Comment by anthonylavado** [comment]
@rudford Since I handle all our API keys and 3rd party accounts, I figure I should ask this: I don't see a way to generate a new ID/Secret from the Applications page. Is there a way we can arrange this?
Though automatic plugin updates are enabled by default, we can't be sure _everyone_ updates. If we just enable the existing one, you'll likely still be flooded.

**Comment by oddstr13** [comment]
> @Shadowghost Just to make sure I'm understanding, the scrobble event is intentionally sent every 5s? If so, that can be removed and this would be fixed I think. We only require one start event to be sent.
> 
> Apologies if I misunderstood!

As I understand it, the intent is to send an explicit update if the playback position jumps more than 5s (user skipped a section, the intro/credits or some such).

It's possible the logic around this isn't 100% sane, but it could also be possible that the server isn't getting the position updates from the client often enough not to trigger the skip detection (I haven't completely wrapped my head around this code yet)

**Comment by rudf0rd** [comment]
@Shadowghost I see!  So this is strictly to be accurate on the progress indicator on Trakt.  If it makes sense to you, maybe 60s would be better?  I don't know the architecture like you do, but it seems to me that the need for that kind of accuracy doesn't match the impact it can have on the API.  Of course I'm being overprotective of the API resources :D

@anthonylavado I was thinking the same.  If it's cool with you, I can regenerate the API key and you can grab it off your app settings.

**Comment by anthonylavado** [comment]
@rudf0rd re:API Key - Sounds good.

Re: updating progress - we're currently exploring how this is working across all our different clients. We'll sort something out soon.

**Comment by rudf0rd** [comment]
@anthonylavado updated

**Comment by Gylesie** [comment]
> @Gylesie are you seeing `Trakt.ServerMediator: Playback skipped` along with the sending movie playback status update message every 6s?

Yes, exactly, even though the playback was continuous. As @Shadowghost pointed out, maybe the client is too slow with the update events. In this particular case it was the Jellyfin Media Player client.

Logs:
```
[DBG] [32] Trakt.ServerMediator: Playback progressed
[DBG] [32] Trakt.ServerMediator: User "xxxxx" progressed watching item "xxxxxxxxxxxxxxxxxxxxxxxxxx".
[DBG] [32] Trakt.ServerMediator: Playback skipped
[DBG] [32] Trakt.ServerMediator: Sending episode playback status update to trakt.tv for user "xxxxx".
[DBG] [32] Trakt.Api.TraktApi: TraktScrobbleEpisode { xxxxxxxxx }
```

There were no skips.

**Comment by Shadowghost** [comment]
Progress intervals of some of our apps (sourced from our Matrix chat):
* Jellyfin-web: less than 10 seconds (only from memory)
* Jellycon: 10 seconds
* Jellyfin4Kodi: 11 seconds
* Roku: 30 seconds
* Mopidy: 1 Minute

I pushed a PR which now compares timestampps difference of the events to the difference between ticks to check for skips. It's untested, so feel free to test and comment until I find the time to do it myself tomorrow.

**Comment by anthonylavado** [comment]
@rudf0rd I see we got a new Client ID, but not a new Client Secret. Was that intentional? Our auth tests are currently failing.

**Comment by rudf0rd** [comment]
Apologies.  Forgot to approve the app.  Should be good now.

- Sean

**Comment by zaourzag** [comment]
I ended up creating a fork to mitigate the rate limit issues. You can find it [here](https://github.com/zaourzag/jellyfin-plugin-trakt/releases/tag/v21.0.1.0) this will be updates from time to time.the only difference is that it has my own creds

**Comment by TastyPi** [comment]
Would it be worth allowing people to provide their own API keys to avoid this in the future?

**Comment by foux** [comment]
I don't think it's a good idea. If another issue appears with the code, there will be a lot of keys out there, and Trakt won't be able to invalidate them all easily.

**Comment by daullmer** [comment]
None of the proposed solutions would fix the underlying problem. The fork @zaourzag created only changes the keys. While this would allow the forked plugin to work if Trakt disabled the Jellyfin key again, it wouldn't fix the problem that the plugin is hammering the Trakt API.

**Comment by foux** [comment]
What hammering are you talking about? This issue was fixed 11 days ago on version 21.

**Comment by daullmer** [comment]
It is fixed now. But if there would still be a problem, the fork or allowing people to provide their own keys would do absolutely nothing.
