### ISSUE TITLE
Removed Plays

### ISSUE THREAD

**Issue by TJSoler** [jellyfin/jellyfin-plugin-trakt#36]
I've been having problems where my plays (scrobbles) have been removed from my history, even old ones that had nothing to do with jellyfin. I emailed support at trakt and seemed like the app removing those playthroughs is Jellyfin.

I will be having a look at this, see if I can fix it, but I wanted to open the discussion to see if anyone else was having a look at this or if there were any pointers, as it's my first time with this project, will take me a while to wrap my head around the main project and the plugins.

Seems to be related to #15 and fixed by #17, but this happened to me during Christmas and January. So I will be having a look anyway.

**Comment by bpepple** [comment]
Been experiencing this same bug, but haven't been able to diagnose what's causing it.

**Comment by bpepple** [comment]
Looking at this a bit closer and it looks like the default values for the plugin might be the cause, in particular the following options:

* During Scheduled Task, set Trakt items to unwatched if local item is unwatched
* Set Trakt item to Unwatched when local item is changed to Unwatched.

Maybe they should have a default value of false, since I'm guessing this is why watch statuses are being removed from trakt.

**Comment by mblennegard** [comment]
> * During Scheduled Task, set Trakt items to unwatched if local item is unwatched
> * Set Trakt item to Unwatched when local item is changed to Unwatched.
> 
> Maybe they should have a default value of false, since I'm guessing this is why watch statuses are being removed from trakt.

If it is indeed these default values that are causing the issue, maybe an initial sync _from_ Trakt _to_ Jellyfin could solve the issue, to make sure the Trakt data is actually being used, while still being able to keep the default values.
