### ISSUE TITLE
hey man, do you think we can reuse your code to do the same for tvtime?

### ISSUE THREAD

**Issue by elvis0288** [jellyfin/jellyfin-plugin-trakt#56]

**Comment by elvis0288** [comment]
https://api.tvtime.com/doc here is the API

**Comment by oddstr13** [comment]
Looks like this repository is MIT licensed, so you can do pretty much what you want with the code as long as you preserve the license file in some form.

Plugins, once compiled, effectively become GPLv3 due to linking into the Jellyfin source, however ([see commit message in the template repo](https://github.com/jellyfin/jellyfin-plugin-template/commit/618b1d57d5ee22c84d53b94acda83faba323a302) updating the license there).

Take a look at the overview and license text of [GPLv3](https://choosealicense.com/licenses/gpl-3.0/) and [MIT](https://choosealicense.com/licenses/mit/) for more details on what this means.


There is absolutely nothing hindering forking of this plugin, but keep in mind that the GPL is viral, and this means that as soon as you compile the plugin against Jellyfin (via the nupkg dependencies needed by the plugins) and release it, your plugin binaries become subject to the GPLv3 license, and you need to provide the source code to anyone that request it.

I would recommend keeping the source code on GitHub or similar services, and tagging each release on there, as that would be the lowest effort way of keeping your obligation to provide the source code.

@elvis0288 just have at it! :slightly_smiling_face: 

PS: obligatory [IANAL](https://en.wikipedia.org/wiki/IANAL)

**Comment by cvium** [comment]
This code base is less than ideal. I'd suggest looking elsewhere.
