### ISSUE TITLE
Multi-episode files not marked correctly on Trakt

### ISSUE THREAD

**Issue by foux** [jellyfin/jellyfin-plugin-trakt#77]
When watching a multi-episodes file (ie Episodes 20-21 on the same file), the plugin will only mark the second one as watched on Trakt, and the scrobble won't work

**Comment by Shadowghost** [comment]
In Jellyfin files with multiple episodes aren't handled like two episode instances with different metadata but as one episode entity with one set of metadata which occupies multiple episodes.

Therefore it's impossible for the trakt plugin to know things like:
* When the first episode ended and the second started (syncing playstate to trakt reliably is not possible)
* The ids of the second episode because only one set of metdata is saved (collecting both episodes on trakt is not possible without a lot of additional work)
