### ISSUE TITLE
Sync Collections doesn't remove from Trakt collections when its deleted from library

### ISSUE THREAD

**Issue by arbuilder** [jellyfin/jellyfin-plugin-trakt#84]
currently when we remove item from library ( from jellyfin itself) it doesn't get removed from trakt collections. Can a option be given to remove from trakt collection too if its deleted from jellyfin library ( or from os folder).

It can be implement during scan also:

1) after trakt sync collection is done
2) remove from trakt collections if it isn't in jellyfin

**Comment by Shadowghost** [comment]
We are already syncing deletions.
But I don't think it should be the plugins responsibility to clean up any collected items weren't ever a part of the Jellyfin library.

**Comment by KaiStarkk** [comment]
Can it be an option or additional scheduled task available to hard-sync collection?
Alternatively, does anyone know of a way to empty your trakt collection so that we can start from fresh?

Also just to clarify on above @Shadowghost are deletions synced only if deleted through Jellyfin? I've deleted a few shows through the filesystem and/or Sonarr, and they don't seem to remove from trakt.

**Comment by Shadowghost** [comment]
If the media was scanned into Jellyfin prior to deletion and you scanned after it was removed from the file system it should be synced.
